export const STORAGE_KEY = {
    SESSION_PROFILE: 'SESSION_PROFILE',
    SESSION_STATE_LEVEL_0: 'SESSION_STATE_LEVEL_0',
    SESSION_STATE_LEVEL_1: 'SESSION_STATE_LEVEL_1',
    SESSION_STATE_LEVEL_2: 'SESSION_STATE_LEVEL_2',

    LOCAL_THEME: 'LOCAL_THEME',
    LOCAL_LAYOUT: 'LOCAL_LAYOUT',
    LOCAL_LANGUAGE: 'LOCAL_LANGUAGE'
}
